### ISSUE TITLE
기본적인 사용 방법에 대한 질문

### ISSUE THREAD

**Issue by coleea** [shin285/KOMORAN#11]
안녕하세요. 코모란 잘 사용중인 유저입니다. 감사드리구요..

일반적인 java프로그래밍 환경에서는 잘 실행되는데 안드로이드 환경에서 실행이 안 되어서 질문하나 드립니다

    Komoran komoran = new Komoran("코모란 폴더경로"); 

로 처음에 경로설정을 하는데.. 일반 컴퓨터 환경에서는 그냥 경로를 적으니 되던게 안드로이드 환경에서는 잘 되지 않습니다. 
더 정확히는 경로를 어떻게 설정하면 좋을지 모르겠습니다. 

    getAssets().open("파일명")
으로 파일은 읽어올 수 있겠는데 안드로이드에서 폴더 경로를 얻는 방법은 없는 것 같아 안되나보다 싶었는데 제작자님이 안드로이드에서 정상작동을 확인하셨다고 하여.. 질문드립니다

깃헙 이슈란은 피드백용 게시판으로 알고 있는데 질문글을 올릴 곳을 몰라서 부득이하게 이곳에 올립니다. 죄송하구요.. 좋은 프로그램 감사드립니다 -

**Comment by ysj926** [comment]
지난 이슈이나 다른 분들 참고하실 수 있도록 답변 남깁니다.

new Komoran("Data Dir") // 당연히 PC와 안드로이드 환경이 다르고, Data Dir이 스마트폰 내부에 존재하지 않으므로 안됩니다.

해결방법
1. 프로젝트를 pull 받거나 zip 파일을 받아 models_light 혹은 models_full 내의 파일들을 복사한다.
2. 안드로이드 스튜디오에서 프로젝트를 생성하여, assets 폴더 내에 파일들을 붙여 넣는다.
3. 어플리케이션이 초기화 될 때, assets 폴더의 파일들을 안드로이드의 로컬 저장소에 내의 임의의 폴더에 복사하는 코드를 작성한다. 
4. 임의의 폴더 경로를 "Data Dir" 위치에 넣어준다.

assets 폴더란 : http://recipes4dev.tistory.com/125

참고해보세요
