### ISSUE TITLE
논문 등에 인용할 수 있는 레퍼런스가 있나요?

### ISSUE THREAD

**Issue by papower1** [shin285/KOMORAN#12]
인용할 수 있는 문구 등을 알려주시면 논문 작성하는 데에 도움이 될 것 같습니다. 감사합니다.

**Comment by shin285** [comment]
안녕하세요. 답변이 늦었습니다.

공식적인 규칙은 없으나 대부분 논문에서 아래와 같이 인용구를 삽입하는 것 같습니다.

@misc{komoran,
author = {Junsoo Shin},
title = {komoran},
year = {2016},
publisher = {GitHub},
journal = {GitHub repository},
howpublished = {\url{https://github.com/shin285/KOMORAN}}
}

**Comment by papower1** [comment]
감사합니다. ^^
