### ISSUE TITLE
쓰레드 세이프한 아호코라식을 적용하여도 코모란이 쓰레드 세이프하지 않는 이슈

### ISSUE THREAD

**Issue by shin285** [shin285/KOMORAN#14]
쓰레드 세이프한 아호코라식 트라이를 적용하여 FindContext를 이용함에도 코모란 자체가 쓰레드 세이프 하지 않은 것 같습니다.. 브랜치명은 thread-safed입니다.. 확인 요청드립니다 ㅠ

@jihoonson

**Comment by jihoonson** [comment]
안녕하세요, 혹시 테스트 환경을 공유해주실 수 있을까요? 저도 확인해보겟습니다.

**Comment by shin285** [comment]
브랜치명 thread safe의 테스트 케이스에 해당 테스트 내용이 포함되어있습니다~ 제가 내공이 많이 부족합니다ㅠ

**Comment by shin285** [comment]
analyze 실행 시 getter, setter를 써서 thread safe하지 않는 문제로 확인됐습니다~ 해당 이슈를 close 하겠습니다 :)
