### ISSUE TITLE
KomoranResult의 getTokenList 시 간헐적으로 NullPointException 발생

### ISSUE THREAD

**Issue by shin285** [shin285/KOMORAN#15]
komoran3.0 사용을 위해 테스트 하고 있습니다.
동작은 잘 하는데 특정 글자에서 java.lang.NullPointerException 에러가 발생하고 있습니다.
테스트한 글자는 '센', '센트롤이' 두가지 이구요 '센트롤' 이라고 하면 에러없이 정상작동 합니다.
KomoranResult.java 에서 Second 에 셋팅되지 않아서 에러가 나는것 같습니다.
if(jasoBeginIdx >= syllableAreaList.get(i).getSecond()){
syllableAreaPair.setSecond(i+1);
}

좀 더 추척해봤지만 소스 전체를 다 이해하지 못해서 어떻게 수정해야할지를 모르겠습니다~~
도움 부탁드려요~

**Comment by xtknight** [comment]
Same issue here with tagging just "난".  syllableArea.getSecond() is null

**Comment by shin285** [comment]
@xtknight 현재 해당 이슈는 업데이트 되어서 릴리즈 하였습니다. 따로 이슈를 클로즈 하지 않아서 죄송합니다 :) 더불어 리포팅 감사합니다~

**Comment by xtknight** [comment]
Thank you for your hard work ~~ I confirmed that the null pointer problem is actually fixed. But I didn't make this issue so I can't close it.  I have another issue with token index so I will open a different issue.
