### ISSUE TITLE
이 프로젝트를 gradle  에서 불러오려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by yevgnenll** [shin285/KOMORAN#17]
```
dependencies {
    compile 'com.github.shineware:commons:1.0.0'
    compile 'com.github.shineware:aho-corasick:1.0.5'
}
```

이 두가지를 제외하고 또 무엇을 추가해야할까요??

**Comment by shin285** [comment]
gradle에서 가져가기 위해서는 별도의 플러그인이 필요하며, 추가적으로 komoran도 release가 되어야합니다~ 관련 내용 조만간 업데이트 하겠습니다 :)

**Comment by 9bow** [comment]
repositories에 jitpack을 추가하시고, dependencies에 KOMORAN을 추가하시면 필요한 commons 등을 불러오게 됩니다.

아래 코드를 참고해주세요.
``

**Comment by 9bow** [comment]
불러오신 후의 사용법은 [다음 소스](https://github.com/9bow/KOMORANRestAPIServer/blob/master/src/main/java/api/KOMORANDemo.java)를 참고해주세요. ^^

**Comment by yevgnenll** [comment]
이미 완료해서 잘 사용하였습니다~ ㅎㅎ 감사합니다

**Comment by 9bow** [comment]
뒤늦게 회신드렸네요 ^^; 
많은 활용 부탁드립니다~ Slack도 이용해주시고요 ^^
