### ISSUE TITLE
안녕하세요, 코모란을 써보고 싶은 초보입니다.

### ISSUE THREAD

**Issue by MountainNine** [shin285/KOMORAN#18]
코모란을 안드로이드 스튜디오에 써보고 싶은데

평소 jar 파일을 import하거나 gradle에 코드를 써서 가져오는 정도만 해왔습니다.

그런데 그 밖의 방법으로 어떻게 가져오는 지 잘 모르겠습니다.

부끄럽지만 질문해봅니다.

**Comment by shin285** [comment]
부끄럽다뇨~ gradle에서 사용하실 수 있도록 곧 수정하겠습니다! 감사합니다.

**Comment by ysj926** [comment]
조금 지난 이슈이나 공유 합니다.

root 수준의 gradle 파일에 다음과 같이 추가를 합니다.
	allprojects {
		repositories {
			...
			**maven { url 'https://jitpack.io' }**
		}
	}
