### ISSUE TITLE
Token indexing confusion

### ISSUE THREAD

**Issue by xtknight** [shin285/KOMORAN#19]
Using Komoran-3.1.0 I have run the test code. However I am confused about the meaning of beginIndex and endIndex. I need to retrieve original 어절, however the behavior of beginIndex and endIndex appears to have been changed from a previous version. The endIndex value seems to be too high. Also I am not sure whether endIndex is an inclusive or exclusive range. I'm not sure if it's a bug or not.

Example:

    Token [morph=밀리언 달러 베이비, pos=NNP, beginIndex=0, endIndex=11]
    밀리언 달러 베이비/NNP(0,11)

    >>> '밀리언 달러 베이비랑 바람과 함께 사라지다랑 뭐가 더 재밌었어?'[0:11]
In Python, [0:11] is '*밀리언 달러 베이비*랑' *(it seems like 랑 is extra here)*

    Token [morph=재밌, pos=VA, beginIndex=30, endIndex=33]
    재밌/VA(30,33)

    >>> '밀리언 달러 베이비랑 바람과 함께 사라지다랑 뭐가 더 재밌었어?'[30:33]
[30:33] is '*재밌*었'  *(it seems like 었 is extra here)*

Could you explain the methodology of the token index and how I can get the original 어절?

I want output like:

    밀리언 달러 베이비랑 => (밀리언 달러 베이비/NNP, 랑/JKB)
    재밌었어? => (재밌/VA, 었/EP, 어/EF, ?/SF)

But token index is including too much of the original text.

Full output from Java:

    String input = "밀리언 달러 베이비랑 바람과 함께 사라지다랑 뭐가 더 재밌었어?";

    ==========print 'getTokenList()'==========
    Token [morph=밀리언 달러 베이비, pos=NNP, beginIndex=0, endIndex=11]
    밀리언 달러 베이비/NNP(0,11)

    Token [morph=랑, pos=JKB, beginIndex=10, endIndex=12]
    랑/JKB(10,12)

    Token [morph=바람과 함께 사라지다, pos=NNG, beginIndex=12, endIndex=24]
    바람과 함께 사라지다/NNG(12,24)

    Token [morph=랑, pos=JKB, beginIndex=23, endIndex=25]
    랑/JKB(23,25)

    Token [morph=뭐, pos=NP, beginIndex=25, endIndex=27]
    뭐/NP(25,27)

    Token [morph=가, pos=JKS, beginIndex=26, endIndex=28]
    가/JKS(26,28)

    Token [morph=더, pos=MAG, beginIndex=28, endIndex=30]
    더/MAG(28,30)

    Token [morph=재밌, pos=VA, beginIndex=30, endIndex=33]
    재밌/VA(30,33)

    Token [morph=었, pos=EP, beginIndex=32, endIndex=34]
    었/EP(32,34)

    Token [morph=어, pos=EF, beginIndex=33, endIndex=35]
    어/EF(33,35)

    Token [morph=?, pos=SF, beginIndex=34, endIndex=35]
    ?/SF(34,35)

    ==========print 'getNouns()'==========
    [밀리언 달러 베이비, 바람과 함께 사라지다]

    ==========print 'getPlainText()'==========
    밀리언 달러 베이비/NNP 랑/JKB 바람과 함께 사라지다/NNG 랑/JKB 뭐/NP 가/JKS 더/MAG 재밌/VA 었/EP 어/EF ?/SF

    ==========print 'getList()'==========
    [Pair [first=밀리언 달러 베이비, second=NNP], Pair [first=랑, second=JKB], Pair [first=바람과 함께 사라지다, second=NNG], Pair [first=랑, second=JKB], Pair [first=뭐, second=NP], Pair [first=가, second=JKS], Pair [first=더, second=MAG], Pair [first=재밌, second=VA], Pair [first=었, second=EP], Pair [first=어, second=EF], Pair [first=?, second=SF]]

**Comment by shin285** [comment]
이슈 감사드립니다! 버그였습니다..ㅠㅠ end index 범위를 잡을 때 '<'를 썼어야 했는데 '<='를 써서 문제가 발생했습니다. 아무래도 정신이 멀쩡하지 않은채로 릴리즈를 했던 것 같습니다.. ㅠㅠ master branch 확인 해 보시고 이슈 있으시면 다시 댓글 부탁드립니다~! 이슈가 없다면 close 부탁드립니다 :)

**Comment by xtknight** [comment]
Thanks for your quick response! I have been testing this with a large data set, so I think that's why I keep coming across certain issues. The issue appears to be fixed.

I just have a question about how "해드려요" and "한다고요" appear to be split differently.

<> contains string[tokenBegin:tokenEnd]

13 16 드리 VX <드려요>   -- here token index is same
13 16 어요 EC <드려요>

My code detects token index begin/end is same, so I avoid duplicating original token.

31 32 하 VV <한>   -- however here token index is different/overlapping
31 34 ㄴ다고 EC <한다고>

My code is confused because tokens are overlapping, so original token is duplicated twice. (한한다고)

Is this a problem? Or should I specially handle these overlapping token indices?

Currently I have code to search for same token index to avoid duplicating the original token, but in the second example token indices are different so I can't tell if I am duplicating the original token. Maybe I need to track each character of the token to determine if the character has been processed?


Full examples:

    "그 말 꼭 할머니한테 해드려요"

    0 1 그 MM <그>
    2 3 말 NNG <말>
    4 5 꼭 MAG <꼭>
    6 9 할머니 NNG <할머니>
    9 11 한테 JKB <한테>
    12 13 하 VV <해>
    12 13 아 EC <해>
    13 16 드리 VX <드려요>
    13 16 어요 EC <드려요>

    "집안이 작은 사업을 하고 있단 이유로기를 쓰고 만나려고 한다고요"

    0 2 집안 NNG <집안>
    2 3 이 JKS <이>
    4 5 작 VA <작>
    5 6 은 ETM <은>
    7 9 사업 NNG <사업>
    9 10 을 JKO <을>
    11 12 하 VV <하>
    12 13 고 EC <고>
    14 15 있 VV <있>
    15 16 단 ETM <단>
    17 19 이유 NNG <이유>
    19 21 로기 NNP <로기>
    21 22 를 JKO <를>
    23 24 쓰 VV <쓰>
    24 25 고 EC <고>
    26 28 만나 VV <만나>
    28 30 려고 EC <려고>
    31 32 하 VV <한>
    31 34 ㄴ다고 EC <한다고>
    34 35 요 JX <요>

**Comment by xtknight** [comment]
I found a way to handle the issue in my last comment. I just keep track of the last token index mentioned in the <tokenBegin, tokenEnd> range and avoid adding duplicate. If the current token begin is less than the last token end, I set the current token begin to last token end+1. It seems to fix the issue.

But here's another thing:

It's becoming apparent that Korean is such a difficult language to parse. Maybe I am being too picky but, let's take this example.

    "멋있으세여ㅎㅎ"
    0 6 멋있으세옇ㅎ NA <멋있으세여ㅎ>

The last 'ㅎ' gets glued to the bottom of the 여 to make 옇 but unfortunately I'm not sure if this is desired behavior. (I think it's because you split 자모 internally and recombine.)

Of course usually having 자모 outside like this is rare, but it could be common if we process a Twitter corpus containing lots of informal language like 'ㅋㅋ' or 'ㅎㅎ'. What's the best way to handle this problem?

**Comment by shin285** [comment]
답변이 늦어졌습니다. 죄송합니다. 일단 index가 overlapped 되는 것은 정상적인 출력 결과 입니다.
예를 들어, 
31 32 하 VV <한>
31 34 ㄴ다고 EC <한다고>
와 같은 경우에서

 "하"가 포함된 음절은 "한"이 되기 때문에, "한"이 포함된 음절 index를 반환하게 됩니다.
"ㄴ다고"가 포함된 음절은 "한다고"이기 때문에, "한다고"의 전체 음절 index를 반환하게 됩니다.
하나의 음절이 자모 단위로 쪼개지면서 2개 이상의 형태소를 갖게되어서 나타나는 한글의 특수적인 현상입니다. 
해당 기능은 검색 엔진의 하이라이팅에서 주로 사용될 목적으로 추가되었기 때문에 중복되어서 index 정보가 나타나는 현상은 정상이라고 보셔도 무방할 것 같습니다 :)

아래 코멘트 주신 내용은 버그가 맞습니다 ㅠ 알려진 이슈입니다만, Komoran 내부에서 처리하기 보다 외부에서 외부에서 전처리를 통해 입력을 권장하였었습니다.

그러나 생각보다 같은 이슈를 제기하시는 분들이 많으셔서 조만간 전처리 역할을 하는 로직을 분석 시에 선택적으로 적용할 수 있도록 추가하겠습니다!!

감사합니다 :)

**Comment by xtknight** [comment]
Okay! Yes I understand. Sounds good. Processing Korean has so many interconnected steps like preprocessing, morphological analysis, POS tagging, and dependency parsing, and it's very difficult to find the optimal way to make each one of the tools behave so that all the others work perfectly. Furthermore, there are 동음어 and spelling changes. I think this eventually all needs to be handled somewhere, but for now I think I will close this issue because the original issue is fixed and so far I'm having no trouble using the method I proposed for restoring the original 어절. Thanks again!
