### ISSUE TITLE
n-best 분석 결과 지원

### ISSUE THREAD

**Issue by shin285** [shin285/KOMORAN#25]
안녕하세요 KOMORAN 3.0 유용하게 잘 사용하고 있습니다.
관련해서 여쭤보고 싶은것이 있는데 2.4버전에서 지원하던
n-best 분석결과는 3.0에서 지원하지 않는지 여쭤보고 싶습니다.
또한 analzeTextfile 을 이용할 때 inputfilename에 들어가는 textfile의 경로를
어디에 위치해야하는지도 궁금합니다.
바쁘시겠지만 답변 부탁드리겠습니다. 감사합니다!

출처: http://shineware.tistory.com/ [To. Me]

**Comment by dolpang2** [comment]
@alphajin1

**Comment by dolpang2** [comment]
#44 @shin285 implemented required feature, close ticket.
