### ISSUE TITLE
Maven repository에 라이브러리 적용

### ISSUE THREAD

**Issue by shin285** [shin285/KOMORAN#27]
안녕하세요. Komoran을 사용해서 한국어 텍스트 분석을 해보려고 하는 학생입니다. 학교에서 term project로 한국어 텍스트 분석을 수행하고 있는데, 프로젝트가 Maven 기반으로 작성되어있습니다. 그런데, Komoran은 아직 maven central repository에는 올라가지 않은 모양이더라고요.

혹시 가능하다면 Komoran을 Maven을 통해 사용하도록 하는 계획은 없으신가요?

**Comment by 9bow** [comment]
(maven을 사용해보지는 않았습니다만) 혹시 아래와 같은 방법으로 사용이 되시는지 테스트해봐주실 수 있으신지요? ^^;

repository에 JitPack을 추가해주시고,
```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

dependency에 KOMORAN Repo를 아래와 같이 추가해봐주시기 바랍니다.
```
	<dependency>
	    <groupId>com.github.shin285</groupId>
	    <artifactId> KOMORAN</artifactId>
	    <version>3.3.2</version>
	</dependency>
```

gradle에서도 [JitPack](https://jitpack.io/)을 이용하고 있어서 동일한 방법으로 가능하실 것 같은데요, 번거로우시겠지만 확인 부탁드립니다.

감사합니다. ^^

**Comment by agune** [comment]
안녕하세요 저도 필요해서 찾다가 해당 이슈를 보고 테스트를 했습니다.
저같은 경우는 gradle 환경에서 위와 같은 방법으로  테스트 해보았는데 잘되는것 같습니다.

**Comment by 9bow** [comment]
확인 감사합니다 ^^
