### ISSUE TITLE
초보자가 접근하기 쉽게 README.md 파일을 수정해봐도 될까요?

### ISSUE THREAD

**Issue by blackhands77** [shin285/KOMORAN#28]
초보자가 접근하기 쉽게 README.md 파일을 수정해봐도 될까요?
영어로 해놓으셨으니 영어로 수정해볼까 합니다.

**Comment by shin285** [comment]
Sure! Why not?!
제가 영어가 잘 안되서.. 고민만 하고 있었는데..ㅠ
수정해주시면 더 많은 분들이 사용하실 수 있을 것 같아요!
감사합니다!

**Comment by dolpang2** [comment]
@shin285 

아래 4가지에 관한 내용 추가가 되면 좋을 것 같아요. 어떻게 생각하세요?
3번째와 4번째는 제가 수정할 수 있을 것 같습니다.

- [ ] DEFAULT_MODEL.LIGHT와 DEFAULT_MODEL.FULL의 차이 및 용도 설명 추가

- [ ] setFWDic, setUserDic의 차이, 그리고 받는 파일 포맷의 예제 추가

- [ ] 빌드 도구(Gradle, SBT...)에서 Import 하는 부분 보완 및 추가 ( 관련 중복 Issue #27 )

- [ ] README_ko.md 추가

**Comment by shin285** [comment]
그럼 제가 첫번째랑 두번째 추가하겠습니다~

**Comment by shin285** [comment]
정리하다보니 위키페이지도 필요할 것 같아서 틀만 대충 잡아놨습니다.
https://github.com/shin285/KOMORAN/wiki

**Comment by 9bow** [comment]
@shin285 
wiki 또는 README.md에 내용 채워주시면 별도 문서를 만들어보겠습니다.

**Comment by 9bow** [comment]
README 수정( #50 )과 함께 [KOMORAN 문서 사이트](https://docs.komoran.kr)를 만들게 되어 본 이슈를 닫습니다.
