### ISSUE TITLE
How to use android?

### ISSUE THREAD

**Issue by binbinplay** [shin285/KOMORAN#3]
Hello! I'm developing applications for Korean on android but I can not use your library. Because it out memory.

**Comment by shin285** [comment]
Hello! You should train without wiki title for low memory device. So I recommend skip this line on training "builder.setExternalDic("user_data"+ File.separator+"wiki.titles");" . Please try this :)

**Comment by binbinplay** [comment]
Thanks for the reply. I have tried but can't run.
This my logcat:
I/dalvikvm-heap: Grow heap (frag case) to 54.864MB for 240-byte allocation
D/dalvikvm: GC_FOR_ALLOC freed <1K, 4% free 56105K/58311K, paused 114ms, total 114ms
D/dalvikvm: GC_FOR_ALLOC freed 65K, 4% free 56126K/58311K, paused 81ms, total 81ms

**Comment by shin285** [comment]
I think that the model builder can't run on android. So, I will check it soon. Sorry for the wrong information.

**Comment by binbinplay** [comment]
Thank you so much!
I'm using your library as the Web Service for Android and iOS but speed is not very good. 
Awaiting your early reply and thanking you.

**Comment by shin285** [comment]
When using komoran as the web service, load resource once when the server start. Youn don't need load resource sevaral time. (= Komoran komoran = new Komoran("models");
        komoran.setFWDic("user_data/fwd.user");
        komoran.setUserDic("user_data/dic.user");

**Comment by binbinplay** [comment]
Can you convert to Javascipt language?

**Comment by shin285** [comment]
Sorry, I have no plan convert to Javascript yet.
