### ISSUE TITLE
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by jijih19** [shin285/KOMORAN#34]
안녕하세요 ?
안드로이드 스튜디오에서 코모란을 이용해서 형태소분석을 해보려고 합니다
이클립스트에서는 성공을 했으나 안드로이드스튜디오에서는 계속 실패를 하고 있습니다.
새로운 프로젝트를 생성해서 그곳에서 코모란 형태소를 불러오고 싶어서
jar 을 libs에 추가하고 buil.gradle에 추가작업을 해주고 실행을 했더니
이런 에러가 발생하였습니다

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.> java.lang.RuntimeException: java.lang.RuntimeException:
com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

구글링으로 찾아보았지만 그 방법들 모두 돌아가지 않았습니다

혹시 해결하신분들이 있다면 답변부탁드리겠습니다
정말 감사합니다

**Comment by dolpang2** [comment]
안녕하세요. 문제 해결은 하셨나요?
KOMORAN author는 아니지만 도움을 드리고 싶어서 답글 남깁니다.
사용하시는 OS, Android Studio Version, 소스코드 및 에러 화면 등 조금 더 상세한 자료가 있으면 좋을 것 같습니다.
추가로 혹시 External Jar를 추가하지 않고, jitpack.io를 통해서 maven에서 당겨서 사용은 해보셨나요?

**Comment by jijih19** [comment]
@dolpang2  
maven에서 당겨서 사용은 해보지 않았습니다.
몇일동안 노력하다 문제를 해결하지 못하고 저희가 다른 방법을 찾아서 형태소 분석에 성공하였습니다. 
친절한 답변 정말 감사합니다 !! 앞으로는 질문을 할때 상세한 자료를 첨부해서 답변하시는 분들이 이해하기 쉽게 올리도록 하겠습니다 
감사합니다!!!

**Comment by dolpang2** [comment]
@jijih19 
혹시 다른 우회 방법이 어떤 방법인지 알려주실 수 있을까요? KOMORAN 내부에서 수정이 가능한 부분이면 큰 도움이 될 것 같아서요~

**Comment by ysj926** [comment]
헤결 방법이 될 수 있을지 모르겠지만 참고하시도록 링크 남깁니다.
https://developer.android.com/studio/build/multidex?hl=ko
