### ISSUE TITLE
KOMORAN Spark Wrapper

### ISSUE THREAD

**Issue by dolpang2** [shin285/KOMORAN#36]
안녕하세요. Spark 환경에서 KOMORAN으로 고객 Review를 분석하는 개발자입니다.
제 경우, KOMORAN udf를 만들어서 분석하고 있는데요.
Spark용 Wrapper가 있으면 좋겠다는 생각이 듭니다.
혹시 Spark Wrapper를 작성해서 maven 등에 배포가 가능할까요?
가능하다면, 참고 및 준수해야 할 라이센스 규정 등을 알려주시면 감사하겠습니다.

**Comment by shin285** [comment]
아파치 라이센스이기 때문에 자유롭게 사용가능합니다! Spark에 요구사항이 많아지고 있었는데 maven에 배포해주신다면 큰 도움이 될 것 같습니다!
