### ISSUE TITLE
Suggestion of a method accessibility

### ISSUE THREAD

**Issue by dolpang2** [shin285/KOMORAN#37]
[English follows Korean]
@shin285 안녕하세요. 
최근에 추가된 method `getMorphesByTags`의 메소드 접근성 변경에 대해 제안이 있습니다.
우선 현재 master branch의 코드는 다음과 같습니다.
```java
// KomoranResult.java
...
public List<String> getMorphesByTags(String... str) {
    return this.getMorphesByTags(Arrays.asList(str));
}

private List<String> getMorphesByTags(Collection<String> targetPosCollection) {
    Set<String> targetPosSet = new HashSet<>(targetPosCollection);

    List<String> morphList = new ArrayList<>();
    for (LatticeNode latticeNode : resultNodeList) {
        if (targetPosSet.contains(latticeNode.getTag())) {
            morphList.add(parser.combine(latticeNode.getMorphTag().getMorph()));
        }
    }
    return morphList;
}
...
```
현재 버전에서는 `String... str` 형태의 varagrs 형태의 메소드만 public으로 사용할 수 있는데요.
현재 private로 되어있는 `Collection<String>`을 인자로 받는 method도 public으로 바꿀 수 있을지 여쭤보고 싶습니다.

public으로 오픈 시 제가 생각하는 2가지 장점은 다음과 같습니다.
- 메소드 호출 시 문자열 하드코딩보다 Collection 객체를 전달하는 것을 선호하는 사용자가 있을 수 있다.
- Spark UDF에서 varargs를 지원하는 형태로 만들기가 어려움

특별한 side-effect가 없다면 변경할 수 있을까요?

Hello, KOMORAN Team.
I would like have a suggestion of accessibility change about `getMorphesByTags` recently added.
Current code of master branch is like this.
```java
// KomoranResult.java
...
public List<String> getMorphesByTags(String... str) {
    return this.getMorphesByTags(Arrays.asList(str));
}

private List<String> getMorphesByTags(Collection<String> targetPosCollection) {
    Set<String> targetPosSet = new HashSet<>(targetPosCollection);

    List<String> morphList = new ArrayList<>();
    for (LatticeNode latticeNode : resultNodeList) {
        if (targetPosSet.contains(latticeNode.getTag())) {
            morphList.add(parser.combine(latticeNode.getMorphTag().getMorph()));
        }
    }
    return morphList;
}
...
```
We can only use varargs argument `String... str` method as a public in current version.
Is it possible to change private method that has `Collection<String>` argument to public method?

There may be two advantage if it is change to public method.
- Some users prefer to use collection object than string hard coding when they call a method.
- It is difficult to wrap varargs argument method to make Spark UDF.

Is it ok to change it if there is no side-effect?

**Comment by shin285** [comment]
Thank you for your suggestion. There is no side-effect, I think :). I will update it soon! Thanks!
