### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by GeonYoungKim** [shin285/KOMORAN#40]
안녕하세요 코모란 3을 메이븐 프로젝트에 사용하고 싶은 학생입니다.
<dependency>
			<groupId>com.github.shin285</groupId>
			<artifactId>KOMORAN</artifactId>
			<version>3.3.2</version>
		</dependency>
	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

위 코드 처럼 komoran을 받았는데
analyze메소드 수행 시 NoSuchMethodError가 계속 뜨는데 문제를 모르겠네요....

에러는 아래와 같습니다....

java.lang.NoSuchMethodError: kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.newFindContext()Lkr/co/shineware/ds/aho_corasick/FindContext;
	at kr.co.shineware.nlp.komoran.core.Komoran.analyze(Komoran.java:126)

단지 
		Komoran komoran = new Komoran("C:\\Users\\USER\\Desktop\\models");
		
		KomoranResult result = komoran.analyze("안녕하세요");
이것만 수행하는데 에러가 나네요..

**Comment by dolpang2** [comment]
안녕하세요. 현재 KOMORAN latest version은 3.3.4이며 제가 테스트했을 때 문제 없이 잘 동작합니다. 혹시 버전 바꿔서 테스트해보실 수 있을까요?
