### ISSUE TITLE
bulk 분석에 대한 멀티쓰레딩 지원

### ISSUE THREAD

**Issue by shin285** [shin285/KOMORAN#41]

**Comment by dolpang2** [comment]
lol. I may know why u create this ticket bro :D

**Comment by shin285** [comment]
single sentence에 대한 개선은 불가능한 것으로 판단

**Comment by dolpang2** [comment]
@shin285 We can close this issue, how do u think?

**Comment by shin285** [comment]
@dolpang2 I agree. Thanks.
