### ISSUE TITLE
에러 리포팅

### ISSUE THREAD

**Issue by shin285** [shin285/KOMORAN#43]
형태소 분석 대상 문구 : 코스피지수 코스피지수, 재고순환, 소비자기대지수, 수출입물가비율

행태소 분석 결과 
------------------------------------
Pair [first=코스피, second=NNP]
Pair [first=지수, second=NNG]
Pair [first=코스, second=NNG]
Pair [first=피, second=NNG]
Pair [first=지수, second=NNG]
Pair [first=,, second=SP]
Pair [first=재고, second=NNG]
Pair [first=순환, second=NNG]
Pair [first=,, second=SP]
Pair [first=소비자, second=NNG]
Pair [first=기대, second=NNG]
Pair [first=지수, second=NNG]
Pair [first=,, second=SP]
Pair [first=수출입, second=NNG]
Pair [first=물가, second=NNG]
Pair [first=비율, second=NNG]
------------------------------------

사용자 사전 추가 : "코스피 NNP", "지수	NNG" 2개 추가
기분석 사전 추가 : "코스피지수	코스피/NNP 지수/NNG" 1개 추가

그러나 형태소 분석 결과는 위와 같이 나옵니다. 이상해서 문의좀 드립니다. 해결방법이 있을까요?

**Comment by shin285** [comment]
혹시 재현 되시는 분 있으시면 말씀 좀 주세요.

**Comment by dolpang2** [comment]
@shin285 
<img width="347" alt="full-set-fwdic-set-userdic" src="https://user-images.githubusercontent.com/9076745/52518355-f2ad5480-2c8c-11e9-9b02-7a5360dfce72.png">
<img width="366" alt="light-set-fwdic-set-userdic" src="https://user-images.githubusercontent.com/9076745/52518357-f2ad5480-2c8c-11e9-98a0-5ec58e4ba1e9.png">
<img width="344" alt="full-set-fwdic-no-userdic" src="https://user-images.githubusercontent.com/9076745/52518358-f2ad5480-2c8c-11e9-911c-a5c34fd4038f.png">
<img width="345" alt="light-set-fwdic-no-userdic" src="https://user-images.githubusercontent.com/9076745/52518359-f345eb00-2c8c-11e9-9106-714e83cfd5c7.png">
<img width="342" alt="full-no-fwdic-set-userdic" src="https://user-images.githubusercontent.com/9076745/52518360-f345eb00-2c8c-11e9-9a25-0b9837b4960f.png">
<img width="348" alt="light-no-fwdic-set-userdic" src="https://user-images.githubusercontent.com/9076745/52518361-f3de8180-2c8c-11e9-9baa-4f315c221586.png">
<img width="327" alt="full-no-fwdic-no-userdic" src="https://user-images.githubusercontent.com/9076745/52518362-f4771800-2c8c-11e9-8cf4-918820875f85.png">
<img width="339" alt="light-no-fwdic-no-userdic" src="https://user-images.githubusercontent.com/9076745/52518363-f4771800-2c8c-11e9-8622-f4949ccafbf7.png">

Light / Full & User dic & FW dic 
총 8가지 경우의 수에 대해서 KOMORAN 3.3.4 & MacOS 환경에서 테스트해봤습니다.
일치하는 케이스는 Light / Set FW dic / No User dic 인 케이스랑 일치하고
스펙상으로는 제대로 분석한 것으로 보입니다 (코스피지수와 코스피지수, 는 다르죠...)
아마 버그리포팅을 하신 분은 User dic 세팅이 제대로 안된 것으로 보입니다.

**Comment by dolpang2** [comment]
이건과 별개로 User dic과 FW dic의 양식이 좀 불편할 수 있겠다는 생각은 드네요. Tab-separated 파일이 쉽게 만들기 어려울 수 있을 것 같습니다 (일반인 입장에서)

**Comment by shin285** [comment]
[Kor]
@dolpang2 확인 감사드립니다. 말씀하신 user dic과 fw dic을 편집할 수 있는 툴을 현재 @9bow 님께서 개발 중입니다. 조만간 KOMORAN에 merge 될 예정입니다.

[Eng]
Thank you for check this issue. User dictionary and FW dictionary are under developing by @9bow. It will be merge in KOMORAN repository soon.

**Comment by dolpang2** [comment]
Sounds good :) Close this issue
