### ISSUE TITLE
Need to clean up the README

### ISSUE THREAD

**Issue by 9bow** [shin285/KOMORAN#48]
`README.md` contains various contents including installation and usage,
so it is necessary to clean up.

I suggest the following progress:
1. Transfer some content to [komoran / docs](/komoran/docs) (official document)
2. Keep the README concise
3. Translate as many languages as possible (including Korean)

---

KOMORAN README 파일 내에 사용법을 비롯하여 다양한 내용들이 혼재되어 있어, 이를 정리하는 것이 필요합니다.

다음과 같은 진행을 제안합니다.

1. [komoran / docs](/komoran/docs)로 일부 내용을 이관합니다.
2. README를 간결하게 정리합니다.
3. 가능한 다양한 언어(한국어 등)로 번역합니다.

**Comment by 9bow** [comment]
예제를 다음의 [공식 문서 사이트](https://docs.komoran.kr)로 이관하였습니다.

* [분석 예제](https://docs.komoran.kr/examples/analyze.html)
* [모델 학습 예제](https://docs.komoran.kr/examples/train-model.html)
* [Spark2 분석 예제](https://docs.komoran.kr/examples/spark2-scala.html)

@shin285 @dolpang2 
위 문서들 중 수정이 필요하거나 추가하실 내용이 있으면 [docs repo](/komoran/docs)에 PR 부탁드립니다.

**Comment by shin285** [comment]
해당 이슈는 Merge 되었기 때문에 닫겠습니다.

This issue resolved and merged. So I close this issue.
