### ISSUE TITLE
ModelBuilder의 Observation 값 계산에 대한 질문입니다

### ISSUE THREAD

**Issue by jihoonson** [shin285/KOMORAN#5]
안녕하세요, 질문을 어디에 드려야할지 몰라 여기에 남깁니다. 혹시 다른 더 좋은 곳이 있다면 알려주세요..

현재 Baum-Welch 알고리즘을 사용하여 코모란의 HMM 모델을 러닝하고 있습니다.
러닝된 값을 코모란에서 읽을 수 있도록 저장하는데, 다음의 observation을 계산하는 부분이 잘 이해되지 않아 질문드립니다. (https://github.com/shin285/KOMORAN/blob/master/src/main/java/kr/co/shineware/nlp/komoran/modeler/builder/ModelBuilder.java#L215)

```
private void calObservation(Map<String, Integer> totalPrevPOSTf) {

    this.observation = new Observation();

    Set<Entry<String, Map<String,Integer>>> wordDicEntrySet = wordDic.getDictionary().entrySet();
    for (Entry<String, Map<String, Integer>> wordPosTfEntry : wordDicEntrySet) {
        String word = wordPosTfEntry.getKey();
        Set<Entry<String,Integer>> posTfSet = wordPosTfEntry.getValue().entrySet();
        for (Entry<String, Integer> posTf : posTfSet) {
            int totalPosTf = totalPrevPOSTf.get(posTf.getKey());
            double observationScore = (double)posTf.getValue()/totalPosTf;
            observationScore = Math.log10(observationScore);
            this.observation.put(word,posTf.getKey(),this.table.getId(posTf.getKey()),observationScore);
        }
    }
}
```

이 함수에서 입력으로 들어오는 `totalPrevPOSTf`는 grammar 파일로부터 계산된 값으로 보입니다. 이 값을 사용하여 observation 값을 normalization 하는 것처럼 보이는데, 여기에 대해 좀 더 부연 설명해주실 수 있을까요?

감사합니다.

**Comment by shin285** [comment]
totalPrevPOSTf는 observation 값을 계산하기 위한 분모로 사용됩니다. 즉, normalization은 아니고 observation probability를 구하기 위한 factor입니다~

답변이 늦어져서 죄송합니다 ㅠ

**Comment by shin285** [comment]
해당 이슈 닫도록 하겠습니다 대롱님 ㅎㅎ

**Comment by jihoonson** [comment]
넵 ㅎㅎ 저도 답변이 늦었네요. 알려주셔서 감사합니다 :)
