### ISSUE TITLE
기분석 사전 적용 시의 분석 결과 이슈

### ISSUE THREAD

**Issue by 9bow** [shin285/KOMORAN#54]
기분석 사전(`fwd.user`) 적용 시, 분석 결과가 이상하게 표현되고 있습니다.

기분석 사전 적용 전
`[테스트/NNP(0,3), 단어/NNG(4,6)]`

기분석 사전
`테/NNG 스/NNG 트/NNG`

기분석 사전 적용 후
`[테/NNG(0,3), 스/NNG(0,3), 트/NNG(0,3), 단어/NNG(4,6)]`

각 Token의 beginIndex와 endInex가 기분석 사전 적용 전과 동일한 것이 이슈로,
기분석 사전 적용 후 인덱스에 대한 재계산이 필요해보입니다.

**Comment by shin285** [comment]
기분석 사전의 key와 value의 스트링 서로 다르면 value에 해당하는 인덱스를  key에서 찾을 수 없기 때문에 위와 같이 처리하였습니다.
아래 예제와 같은 경우입니다.
`테스트  테/NNG 슽으다/NNG`
그러나 위와 같이 key와 value가 다른 경우에 대해서는 최대한 처리하도록 수정하겠습니다.

**Comment by 9bow** [comment]
이슈 생성 시점에는 자모를 나눠 인덱싱을 하면 될 것이라고 나이브하게 생각했는데, 알려주신 예제 등을 고려해보니 현실적으로 쉽지 않을 것 같기는 하네요.
어떤 케이스에서는 되고, 어떤 케이스에서는 안되는 형태로 진행하는 것보다는 정책을 정하는 것이 낫지 않을까 싶은데요, 우선 #55 PR과 이 이슈는 다음 주 수요일에 있을 정기 모임 때 논의하면 어떨까 싶습니다. @shin285 @dolpang2

**Comment by shin285** [comment]
이슈에서 언급해주신 내용은 확실히 단점이기 때문에 가능하면 인덱스가 맞게 수정 되어야 할 것 같습니다. 제가 언급한 이슈에 대해서만 같이 의논해보시는게 어떨까요?

**Comment by 9bow** [comment]
네, 우선 Action Items 보드에 [이번 이슈](https://github.com/orgs/shineware/projects/1#card-19595973)를 생성해두었습니다.
말씀하신 것처럼 좀 더 논의 주제를 구체화해주시고, 정기 모임 때 논의하면 될 것 같습니다.

**Comment by 9bow** [comment]
현재까지 변경 사항(#55 )을 먼저 반영하였습니다.
정기 모임의 협의 내용을 추가 반영하기 위해 이슈를 다시 열었습니다.

**Comment by 9bow** [comment]
현재까지 논의/적용된 내용을 스펙으로 정하고 본 이슈를 닫습니다.
기분석 사전 적용 시 속도와 관련한 이슈가 있지 않을까에 대한 의견도 있었으나 큰 차이가 없다는 결과가 있어 추가 구조 변경은 하지 않기로 하였습니다.
