### ISSUE TITLE
코모란을 사용해 보고싶습니다.

### ISSUE THREAD

**Issue by mjxaone** [shin285/KOMORAN#6]
웹 페이지내 한글 색인을 정리하기 위해 사용해 보려고 하는데요,
형태소 분석기에 대해 지식이 거의 없습니다.

혹시 코모란에서 트레이닝 샘플이 있던데,
트레이닝을 통해
코모란에 어떤 영향을 끼치는지,
문서나 참고할만한 자료 있을까요?

**Comment by shin285** [comment]
트레이닝 데이터를 직접 수정하시면 수정된 데이터에 가장 적합한 형태소 분석기가 나오게 됩니다.
예를 들어 아재들이 많이 쓰는 단어들의 빈도수(가중치)를 높여주면 아재들의 단어들은 잘 분석하지만 어린 친구들의 단어는 잘 분석하지 못하게 됩니다. 

죄송스럽게도 이와 관련된 문서는 따로 만들지 않았습니다만, 조만간 가이드를 만들도록 하겠습니다.

제가 제대로 이해를 했다면 웹 페이지에 있는 한글 색인어를 추출하시고 싶다는 말씀이신 것 같은데,

웹페이지가 특정한 도메인에 대한 컨텐츠로 구성되어 있지 않다면 (게임, 종교, 정치 등) 그대로 사용하셔도 크게 무리는 없을 것 같습니다~

다만, 새로 발생되는 단어(신조어)나 특정 인물, 집단, 용어 (미등록어) 들은 꾸준히 관리를 해주셔야 합니다~

답변이 되었는지 모르겠네요 :)

더 궁금한게 있으시면 코멘트 부탁드립니다~

**Comment by mjxaone** [comment]
회신 감사드립니다. 코모란을 이용하여 한번 진행해 봐야겠습니다. :D
앞으로도 여러가지 부탁드릴께요. :ㅁ
