### ISSUE TITLE
내부 사전은 어떻게 구성되어 있는지요?

### ISSUE THREAD

**Issue by zidane100e** [shin285/KOMORAN#68]
## 내부 사전 단어 확인 방법 질문
안녕하세요 좋은 자료를 이렇게 만들어 주셔서 너무 감사합니다.
komoran 사용에 앞서 궁금한 점이 있어 문의 드립니다. 

* 질문1 : 사용자 사전에 추가하기전 해당 단어가 이미 사전에 있는지 확인 하고 싶습니다.  
soynlp 등에서 word extractor나 noun extractor 을 제공합니다. 이런 것을 활용해 자동적으로 새 단어들을 생성하고 싶습니다.  
이렇게 찾아주는 전체 단어를 사용자 사전에 넣는 것은 비효율적일 것 같고, soynlp 에서 찾아주는 단어들이 기존 사전에 있는지만 확인하여 없는 것들만 넣어 주는 것이 나을 것 같은데 기존 사전 포함 여부를 어떻게 알 수 있는지 궁금합니다.  
또 이렇게 추가 단어를 넣는 경우도 지속적으로 쓸 경우에는 기존 사전에 넣는 것이 좋을 것 같은데 어떻게 처리할 수 있을지 궁금합니다.

* 질문 2
소스코드를 보면 corpus_build 폴더에 사전과 같은 형태가 있습니다.  
혹시 해당 사전에 제가 단어를 추가하면 되는 것인지요?  
kkoma의 사전을 보면 수십만개 이상의 단어들이 있습니다. Komoran corpus_build 에는 6만여 단어 정도만 보입니다. kkoma 의 단어들을 komoran 에 붙여 넣으면 될까요? 품사 태그도 다르고, 단어 형태소들도 다를 것 같은데 그냥 붙여 넣으면 될까요?

바쁘시겠지만 시간 되시면 알려주시면 큰 도움이 될 것 같습니다.
읽어 주셔서 감사합니다.

**Comment by shin285** [comment]
안녕하세요. 답변드리겠습니다.
- 답변 1: 사용자 사전이 아닌 학습 데이터에 단어들을 추가하여 학습하시면 가능합니다. 
[KOMORAN 학습](https://docs.komoran.kr/examples/train-model.html) 페이지를 참고하시어 학습하실 수 있습니다. 질문2에서 말씀하신 corpus_build/dic.word에 해당 단어를 추가해주시면 됩니다.

- 답변 2: 답변1과 같이 단어를 추가하면 가능합니다만, 품사 태그는 일치해야합니다.

답변이 충분히 됐는지 모르겠습니다.

혹시 추가적으로 질문이 있으시면 부담없이 알려주세요 :)

**Comment by zidane100e** [comment]
답변주셔서 감사합니다

**Comment by zidane100e** [comment]
안녕하세요
dic.word 에서 오른쪽에 있는 숫자는 무엇입니까? 
만약 빈도 같은 것이라면 크기의 기준이 어떻게 되는 것인지요?

**Comment by shin285** [comment]
오른쪽에 있는 숫자는 빈도수입니다. 빈도수는 트레이닝 데이터에서 해당 단어가 출현한 수 입니다. 숫자를 10만큼 증가시킨다고 가정하면 트레이닝 데이터에서 해당 단어가 10번 더 나온 것과 동일한 효과를 얻습니다. 로우레벨 트레이닝 데이터는 공개하고 있지 않습니다. 양해부탁드립니다 :)
