### ISSUE TITLE
Android Stduio에서 컴파일시 클래스 충돌이 발생합니다.

### ISSUE THREAD

**Issue by Oasis1819** [shin285/KOMORAN#69]
## 문제 설명
https://github.com/shin285/KOMORAN/issues/18
Kotlin(안드로이드 스튜디오)에서 KOMORAN을 사용하면 컴파일 시 클래스 충돌이 일어납니다.
구글링을 거쳐본 결과, 코틀린에서 자바 라이브러리 등을 연결하면 그렇다고 하는 일부 의견도 있던데, 이 라이브러리만 이렇게 동작을 하는지라 그거랑은 다른 문제인거 같습니다..

어떤 문제이고 어떤 방식으로 해결하면 될지 조언해주시면 감사하겠습니다! 😃 
## 재현 경로
**프로젝트 단위 그레이들**
`repositories {
       ....
        maven { url 'https://jitpack.io' }
  }`

**앱단위 그레이들**
`dependencies {
    .... implementation 'com.github.shin285:KOMORAN:3.3.3'
}`

설정 후 코드에서 import조차 하지않고 바로 실행하였습니다.

## 환경 정보
* OS 종류 / 버전: Android Oreo(개발환경은 Windows)
* 언어 : Kotlin
* Komoran 버전: 3.3.3
* 그레이들 버전: 3.4.0
* 코틀린 버전:1.3.21
* 안드로이드 스튜디오 버전: 3.4.2

## 추가 정보
**로그**
Duplicate class kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and aho-corasick-1.0.9.jar (com.github.shineware:aho-corasick:1.0.9)
Duplicate class kr.co.shineware.ds.aho_corasick.FindContext found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and aho-corasick-1.0.9.jar (com.github.shineware:aho-corasick:1.0.9)
Duplicate class kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and aho-corasick-1.0.9.jar (com.github.shineware:aho-corasick:1.0.9)
Duplicate class kr.co.shineware.util.common.argument.ArgumentUtil found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.collection.MapUtil found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.collection.MapUtil$1 found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.file.FileUtil found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.model.Jaso found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.model.Jaso$TYPE found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.model.Pair found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.model.Syllable found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)
Duplicate class kr.co.shineware.util.common.string.StringUtil found in modules KOMORAN-3.3.3.jar (com.github.shin285:KOMORAN:3.3.3) and commons-1.0.1.jar (com.github.shineware:commons:1.0.1)

**Comment by dolpang2** [comment]
안녕하세요. issue 제보해주셔서 감사합니다. 제가 Android 관련 환경 설정이 되어있지 않아, 실제 테스트해보지 못하고 몇 가지 제안을 드리는 점 미리 양해부탁드립니다.

1. 20190907 기준으로 최신 KOMORAN 버전은 3.3.4이므로 버전 수정 후 다시 빌드 테스트 시도
2. Gradle 옵션 수정

```java
implementation 'com.github.shin285:KOMORAN:3.3.3'
```
을

```java
implementation('com.github.shin285:KOMORAN:3.3.3') {
    exclude group: 'com.github.shineware', module: 'commons'
    exclude group: 'com.github.shineware', module: 'aho-corasick'
}
```
으로 수정 [Gradle Reference](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:excluding_transitive_module_dependencies)

혹시 위 두 방법 중 어떤 것으로 해결 됐다면 어떤 방법으로 해결됐는지 혹은 두 가지 방법 모두 해결되지 않았다면 코멘트 남겨주세요.

**Comment by Oasis1819** [comment]
제안해주신 2번째 방법을 통해 정상적으로 해결하였습니다 :)
감사합니다!
