### ISSUE TITLE
영문이 섞인 문서의 경우 분석이 가능한지 궁금합니다.

### ISSUE THREAD

**Issue by mjxaone** [shin285/KOMORAN#7]
안녕하세요.
이전에 웹 문서 색인화에 코모란을 사용하려고 질문을 올렸었어습니다.
- 혹시 코모란은 한글+영어 가 섞인 문서의 경우의 분석도 지원하나요?

아니면,
- http://shineware.tistory.com/search/EN-POSTA
  영문 형태소 분석기를 보았습니다.
  이것도 혹시 프로젝트를 계속 진행하실 의향이 있으신가요?
  영문쪽 색인화도 필요할것 같아서요.

**Comment by shin285** [comment]
안녕하세요. 코모란만 사용하는 경우에는 영어가 "SL"로 태깅됩니다. 사용자 사전이나 학습 데이터에 영어를 추가하는 경우에는 해당 품사로 태깅됩니다.

그러나 EN-POSTA의 경우에는 따로 적용하지 않았으며, 추후 사용하는 곳이 많아지게 되면 프로젝트를 계속 진행할 예정입니다~ 감사합니다!

**Comment by mjxaone** [comment]
회신 감사드립니다. 👍
