### ISSUE TITLE
komoran.setUserDic  에서 dic.user  파일을 읽을수 없습니다ㅠ

### ISSUE THREAD

**Issue by buk4130** [shin285/KOMORAN#8]
java에서 Exception in thread "main" java.lang.NoSuchMethodError: kr.co.shineware.nlp.komoran.modeler.model.Observation.put(Ljava/lang/String;ID)V
	at kr.co.shineware.nlp.komoran.core.analyzer.Komoran.setUserDic(Unknown Source)
	at text.Test.main(Test.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
계속 이런 오류가 납니다ㅠ

**Comment by shin285** [comment]
일단 오류 내용만 봐서는 일반적으로 리포팅 되던 상황은 아닌 것 같은데요..혹시 사용하시고자하는 플랫폼(윈도우, 안드로이드, 리눅스 등)과 사용자 파일을 사용하는 부분의 소스를 알려주실 수 있을까요?

**Comment by buk4130** [comment]
일단 저는 MAC os를 사용하고 있습니다!

사용 하고 있는 부분의 소스는

package text;

import kr.co.shineware.nlp.komoran.core.analyzer.Komoran;
import kr.co.shineware.nlp.komoran.model.KomoranResult;
import kr.co.shineware.nlp.komoran.model.Token;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by seonghohong on 2016. 11. 1..
 */
public class Test {
    public static void main(String[] args) {
        Parser test = new Parser();
        ArrayList<String> txt = new ArrayList<String>();
 
        Komoran komoran = new Komoran("src/main/resources");
        komoran.setFWDic("src/main/resources/user_data/fwd.user");
        komoran.setUserDic("src/main/resources/user_data/dic.user");

        String input = "밀리언 달러 베이비랑 바람과 함께 사라지다랑 뭐가 더 재밌었어?";
        List<Token> tokenList = komoran.analyze(input);

        for (Token token : tokenList) {
            System.out.println(token.getMorph());
        }




    }
}

이렇게 됩니다!

**Comment by shin285** [comment]
보내주신 소스를 테스트 해본 결과 문제가 없어 보입니다..안드로이드에서는 테스트를 해보지 못했는데.. 오류 로그를 봐서는 혹시 안드로이드이신지요? 그렇다면 일단 사용자 사전 set하는 부분을 주석 처리 후에 한번 테스트 해주실 수 있으신가요?

**Comment by buk4130** [comment]
아~!  자바로 하고 있었습니다!  이번에 Komoran komoran = new komoran("models"); 에 경로를 주고 하니 정상적으로 작동합니다!  답변이 늦어 져서 죄송합니다ㅠㅠ 감사합니다!!

**Comment by shin285** [comment]
동작한다니 다행이네요~ 해당 이슈 닫도록 하겠습니다~ 감사합니다~
